# Generated by Django 5.2.17 on 2026-08-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма ($)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден (Зачислен)'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('telegram', 'Telegram перевод'), ('crypto', 'Криптовалюта'), ('card', 'Банковская карта')], default='telegram', max_length=30, verbose_name='Метод оплаты')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram аккаунт')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция / Пополнение',
                'verbose_name_plural': 'Транзакции / Пополнения',
                'ordering': ['-created_at'],
            },
        ),
    ]
