# Generated by Django 5.2.17 on 2026-08-31 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция / Запись книги учета', 'verbose_name_plural': 'Журнал транзакций (Ledger)'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс после ($)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс до ($)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание операции'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес инициатора'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID связанного объекта'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение баланса'), ('case_open', 'Открытие кейса'), ('item_sell', 'Продажа скина'), ('sell_all', 'Массовая продажа скинов'), ('upgrade_loss', 'Апгрейд (сгорание скина)'), ('upgrade_win', 'Апгрейд (получение скина)'), ('contract_craft', 'Крафт по контракту'), ('battle_entry', 'Вход в битву кейсов'), ('battle_win', 'Выигрыш в битве кейсов'), ('admin_adjustment', 'Корректировка администратором')], default='deposit', max_length=30, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('system', 'Внутриигровой баланс'), ('telegram', 'Telegram перевод'), ('crypto', 'Криптовалюта'), ('card', 'Банковская карта')], default='telegram', max_length=30, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Успешно завершен'), ('pending', 'Ожидает подтверждения'), ('rejected', 'Отклонен'), ('failed', 'Ошибка транзакции')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
