# Generated by Django 5.2.17 on 2026-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_options_transaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение баланса'), ('case_open', 'Открытие кейса'), ('item_sell', 'Продажа скина'), ('sell_all', 'Массовая продажа скинов'), ('upgrade_loss', 'Апгрейд (сгорание скина)'), ('upgrade_win', 'Апгрейд (получение скина)'), ('contract_craft', 'Крафт по контракту'), ('battle_entry', 'Вход в битву кейсов'), ('battle_win', 'Выигрыш в битве кейсов'), ('promo_bonus', 'Бонус по промокоду'), ('admin_adjustment', 'Корректировка администратором')], default='deposit', max_length=30, verbose_name='Тип операции'),
        ),
    ]
