# Generated by Django 5.2.17 on 2026-09-06 16:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_to_uzs', models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text='Например: 250 (тогда 60 UC = 15 000 UZS)', max_digits=12, verbose_name='Курс: 1 UC в UZS (сум)')),
                ('usd_to_uzs', models.DecimalField(decimal_places=2, default=Decimal('12000.00'), help_text='Например: 12000 (тогда 15 000 UZS ≈ $1.25 USD)', max_digits=12, verbose_name='Курс: 1 USD в UZS (сум)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка курсов валют (UC / UZS / USD)',
                'verbose_name_plural': 'Настройки курсов валют (UC / UZS / USD)',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (UC)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс после (UC)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс до (UC)'),
        ),
    ]
