# Generated by Django 5.2.17 on 2026-09-08 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_bloggerpayout'),
        ('payments', '0004_currencysetting_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Промокод или блогер, через которого пришёл депозит', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='cases.promocode', verbose_name='Промокод / Блогер'),
        ),
    ]
