# Generated by Django 5.2.17 on 2026-09-15 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_promo_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение баланса'), ('case_open', 'Открытие кейса'), ('item_sell', 'Продажа скина'), ('sell_all', 'Массовая продажа скинов'), ('upgrade_loss', 'Апгрейд (сгорание скина)'), ('upgrade_win', 'Апгрейд (получение скина)'), ('contract_craft', 'Крафт по контракту'), ('battle_entry', 'Вход в битву кейсов'), ('battle_win', 'Выигрыш в битве кейсов'), ('promo_bonus', 'Бонус по промокоду'), ('withdraw', 'Вывод средств'), ('admin_adjustment', 'Корректировка администратором')], default='deposit', max_length=30, verbose_name='Тип операции'),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('user_id_val', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма вывода (UC)')),
                ('method', models.CharField(max_length=100, verbose_name='Способ получения')),
                ('details', models.TextField(verbose_name='Реквизиты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Завершено (Выплачено)')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Обработал администратор')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_record', to='payments.transaction', verbose_name='Связанная транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод (Withdrawals)',
                'ordering': ['-created_at'],
            },
        ),
    ]
