# Generated by Django 5.2.17 on 2026-09-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_bloggerpromocode_alter_promocode_bonus_type_and_more'),
        ('payments', '0006_alter_transaction_transaction_type_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UCPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_amount', models.PositiveIntegerField(unique=True, verbose_name='Количество UC')),
                ('price_uzs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая цена (UZS)')),
                ('discount_badge', models.CharField(blank=True, help_text="Например: 'Хит', '+10%', 'Популярный'", max_length=50, null=True, verbose_name='Бейдж скидки / акции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пакет UC',
                'verbose_name_plural': 'Пакеты UC (Uzum Checkout)',
                'ordering': ['order', 'uc_amount'],
            },
        ),
        migrations.CreateModel(
            name='UzumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Номер заказа (NEONDROP)')),
                ('uc_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество UC')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма к оплате (UZS)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], db_index=True, default='pending', max_length=20, verbose_name='Статус платежа')),
                ('uzum_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID заказа в Uzum (orderId)')),
                ('payment_redirect_url', models.TextField(blank=True, null=True, verbose_name='Ссылка на оплату Uzum')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Ключ идемпотентности')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес инициатора')),
                ('raw_callback_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные callback/webhook')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Текст ошибки / причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата успешной оплаты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.ucpackage', verbose_name='Пакет UC')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzum_payments', to='cases.promocode', verbose_name='Промокод блогера')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzum_payment_record', to='payments.transaction', verbose_name='Связанная транзакция в Ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzum_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж Uzum Checkout',
                'verbose_name_plural': 'Платежи Uzum Checkout',
                'ordering': ['-created_at'],
            },
        ),
    ]
