# Generated by Django 5.2.17 on 2026-09-06 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, verbose_name='Баланс (UC)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_winnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма выигрышей (UC)'),
        ),
    ]
