# Generated by Django 5.2.17 on 2026-09-08 08:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_googleaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12, verbose_name='Баланс (UC)'),
        ),
        migrations.CreateModel(
            name='AdminPermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='Просматривать пользователей')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='Редактировать пользователей')),
                ('can_view_cases', models.BooleanField(default=False, verbose_name='Просматривать кейсы')),
                ('can_add_cases', models.BooleanField(default=False, verbose_name='Добавлять кейсы')),
                ('can_edit_cases', models.BooleanField(default=False, verbose_name='Редактировать кейсы')),
                ('can_delete_cases', models.BooleanField(default=False, verbose_name='Удалять кейсы')),
                ('can_add_items', models.BooleanField(default=False, verbose_name='Добавлять предметы')),
                ('can_edit_images', models.BooleanField(default=False, verbose_name='Изменять изображения')),
                ('can_edit_prices', models.BooleanField(default=False, verbose_name='Изменять цены')),
                ('can_edit_case_chances', models.BooleanField(default=False, verbose_name='Изменять шансы кейсов')),
                ('can_manage_promocodes', models.BooleanField(default=False, verbose_name='Управлять промокодами')),
                ('can_view_blogger_stats', models.BooleanField(default=False, verbose_name='Просматривать статистику блогеров')),
                ('can_edit_blogger_percent', models.BooleanField(default=False, verbose_name='Изменять процент блогеров')),
                ('can_view_deposits', models.BooleanField(default=False, verbose_name='Просматривать пополнения')),
                ('can_approve_deposits', models.BooleanField(default=False, verbose_name='Подтверждать пополнения')),
                ('can_view_withdrawals', models.BooleanField(default=False, verbose_name='Просматривать выводы')),
                ('can_approve_withdrawals', models.BooleanField(default=False, verbose_name='Одобрять выводы')),
                ('can_view_backup', models.BooleanField(default=False, verbose_name='Просматривать Backup')),
                ('can_create_backup', models.BooleanField(default=False, verbose_name='Делать Backup')),
                ('can_restore_backup', models.BooleanField(default=False, verbose_name='Восстанавливать Backup')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Права администратора',
                'verbose_name_plural': 'Права администраторов',
                'ordering': ['user__username'],
            },
        ),
    ]
