# Generated by Django 5.2.17 on 2026-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_balance_adminpermissionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissionprofile',
            name='can_run_rng_simulation',
            field=models.BooleanField(default=False, verbose_name='Запускать симуляцию честного серверного RNG'),
        ),
    ]
