databases:
  - name: neondrop-db
    databaseName: neondrop
    user: neondrop_user
    plan: free
    ipAllowList: []

services:
  - type: web
    name: neondrop-ujly
    env: python
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DATABASE_URL
        fromDatabase:
          name: neondrop-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: "False"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
