# Generated by Django 5.2.17 on 2026-08-31 18:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_count', models.PositiveIntegerField(default=1, verbose_name='Количество раундов (кейсов)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость участия ($)')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('in_progress', 'Идет битва'), ('finished', 'Завершена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('is_bot_opponent', models.BooleanField(default=False, verbose_name='Против бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='cases.case', verbose_name='Кейс')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Битва кейсов',
                'verbose_name_plural': 'Битвы кейсов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattlePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот')),
                ('bot_name', models.CharField(default='CyberBot', max_length=100, verbose_name='Имя бота')),
                ('total_loot_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итоговый выигрыш ($)')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='battles.battle', verbose_name='Битва')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Номер раунда')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='battles.battle', verbose_name='Битва')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.item', verbose_name='Выпавший скин')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_drops', to='battles.battleplayer', verbose_name='Игрок')),
            ],
            options={
                'ordering': ['round_number', 'id'],
            },
        ),
    ]
