# Generated by Django 5.2.17 on 2026-09-06 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость участия (UC)'),
        ),
        migrations.AlterField(
            model_name='battleplayer',
            name='total_loot_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итоговый выигрыш (UC)'),
        ),
    ]
