# Generated by Django 5.2.17 on 2026-08-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория кейсов',
                'verbose_name_plural': 'Категории кейсов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(default='AK-47', max_length=100, verbose_name='Тип оружия')),
                ('skin_name', models.CharField(default='Asiimov', max_length=100, verbose_name='Название скина')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость ($)')),
                ('rarity', models.CharField(choices=[('knife', '★ Нож / Особое (Золотое)'), ('covert', 'Тайное (Красное)'), ('classified', 'Засекреченное (Розовое)'), ('restricted', 'Запрещенное (Фиолетовое)'), ('mil_spec', 'Армейское качество (Синее)'), ('industrial', 'Промышленное качество (Голубое)'), ('consumer', 'Ширпотреб (Серое)')], default='mil_spec', max_length=30, verbose_name='Редкость')),
                ('rarity_color', models.CharField(default='#4B69FF', max_length=20, verbose_name='Цвет редкости (HEX)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Изображение предмета')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Изображения / SVG ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет / Скин',
                'verbose_name_plural': 'Предметы / Скины',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название кейса')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена открытия ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Изображение кейса')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Изображения / SVG ID')),
                ('color_theme', models.CharField(choices=[('neon-green', 'Neon Green (Зеленый)'), ('cyber-pink', 'Cyber Pink (Розовый/Маджента)'), ('galaxy-purple', 'Galaxy Purple (Фиолетовый)'), ('frost-cyan', 'Frost Cyan (Ледяной циан)'), ('demon-orange', 'Demon Orange (Огненный)'), ('godlike-gold', 'Godlike Gold (Золотой)'), ('luxury-silver', 'Luxury Silver (Серебряный)'), ('supreme-red', 'Supreme Red (Кровавый)')], default='cyber-pink', max_length=30, verbose_name='Цветовая тема')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный кейс (на главной)')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый кейс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена кейса на момент открытия')),
                ('server_seed_hash', models.CharField(max_length=64, verbose_name='SHA256 Server Seed Hash')),
                ('server_seed', models.CharField(max_length=64, verbose_name='Server Seed (Открытый ключ)')),
                ('client_seed', models.CharField(max_length=64, verbose_name='Client Seed (Ключ клиента)')),
                ('nonce', models.PositiveIntegerField(default=1, verbose_name='Nonce')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время открытия')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='cases.case', verbose_name='Кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='cases.item', verbose_name='Выпавший предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История открытия кейса',
                'verbose_name_plural': 'История открытий кейсов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=10.0, verbose_name='Вес шанса выпадения')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_items', to='cases.case', verbose_name='Кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_containments', to='cases.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет в кейсе',
                'verbose_name_plural': 'Предметы в кейсе',
                'ordering': ['-weight'],
                'unique_together': {('case', 'item')},
            },
        ),
    ]
