# Generated by Django 5.2.17 on 2026-09-03 13:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('payments', '0002_alter_transaction_options_transaction_balance_after_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCaseChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=2, help_text='Шанс в процентах (0.01 - 100.00)', max_digits=5, verbose_name='Персональный шанс (%)')),
                ('starts_at', models.DateTimeField(verbose_name='Дата начала')),
                ('expires_at', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_chances', to='cases.case', verbose_name='Кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_chances', to='cases.item', verbose_name='Предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_chances', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персональный шанс (Personal Case Chance)',
                'verbose_name_plural': 'Персональные шансы (Personal Case Chances)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Промокод')),
                ('bonus_type', models.CharField(choices=[('coins', 'Coins / Баланс ($)'), ('percentage', 'Процент к депозиту (%)'), ('free_case_opens', 'Бесплатные открытия кейса')], default='coins', max_length=30, verbose_name='Тип бонуса')),
                ('bonus_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение бонуса (Coins / % / Кол-во)')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Максимум использований (всего)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('starts_at', models.DateTimeField(verbose_name='Дата начала')),
                ('expires_at', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('min_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Мин. депозит для активации ($)')),
                ('max_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. сумма бонуса ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='cases.case', verbose_name='Кейс для бесплатных открытий')),
            ],
            options={
                'verbose_name': 'Промокод (Promo Code)',
                'verbose_name_plural': 'Промокоды (Promo Codes)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Начисленный бонус')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='cases.promocode', verbose_name='Промокод')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocode_uses', to='payments.transaction', verbose_name='Связанная транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_uses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-used_at'],
                'unique_together': {('user', 'promo_code')},
            },
        ),
        migrations.CreateModel(
            name='UserFreeOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openings_left', models.PositiveIntegerField(default=0, verbose_name='Осталось бесплатных открытий')),
                ('total_granted', models.PositiveIntegerField(default=0, verbose_name='Всего начислено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_free_openings', to='cases.case', verbose_name='Кейс')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_openings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бесплатные открытия пользователя',
                'verbose_name_plural': 'Бесплатные открытия пользователей',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'case')},
            },
        ),
    ]
