# Generated by Django 5.2.17 on 2026-09-06 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_personalcasechance_promocode_promocodeuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена открытия (UC)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (UC)'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена кейса на момент открытия (UC)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='bonus_type',
            field=models.CharField(choices=[('coins', 'UC / Баланс (UC)'), ('percentage', 'Процент к депозиту (%)'), ('free_case_opens', 'Бесплатные открытия кейса')], default='coins', max_length=30, verbose_name='Тип бонуса'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='bonus_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение бонуса (UC / % / Кол-во)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. сумма бонуса (UC)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Мин. депозит для активации (UC)'),
        ),
        migrations.AlterField(
            model_name='promocodeuse',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Начисленный бонус (UC)'),
        ),
    ]
