# Generated by Django 5.2.17 on 2026-09-06 18:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_price_alter_item_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='blogger_name',
            field=models.CharField(blank=True, help_text='Например: YouTube @BloggerName или Telegram @channel', max_length=150, null=True, verbose_name='Имя / Канал блогера'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='blogger_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Процент от чистого проигрыша привлеченных пользователей (например: 10.00 = 10%)', max_digits=5, verbose_name='Процент блогера (%)'),
        ),
    ]
