# Generated by Django 5.2.17 on 2026-09-08 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_promocode_blogger_name_promocode_blogger_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма выплаты (UC)')),
                ('period', models.CharField(help_text='Например: 2026-09 или all_time', max_length=30, verbose_name='Период выплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий / Реквизиты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выплаты')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogger_payouts_made', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='cases.promocode', verbose_name='Промокод / Блогер')),
            ],
            options={
                'verbose_name': 'Выплата блогеру',
                'verbose_name_plural': 'Выплаты блогерам',
                'ordering': ['-created_at'],
            },
        ),
    ]
