# Generated by Django 5.2.17 on 2026-09-08 19:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_bloggerpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RngSimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_simulations', models.PositiveIntegerField(verbose_name='Количество симуляций')),
                ('case_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена кейса (UC)')),
                ('target_rtp', models.FloatField(verbose_name='Target RTP (%)')),
                ('actual_rtp', models.FloatField(verbose_name='Actual RTP (%)')),
                ('deviation', models.FloatField(verbose_name='Отклонение (%)')),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Потрачено (UC)')),
                ('total_payout', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Выплачено (UC)')),
                ('house_edge', models.FloatField(verbose_name='House Edge (%)')),
                ('chi_square_stat', models.FloatField(verbose_name='Chi-Square статистика')),
                ('p_value', models.FloatField(verbose_name='p-value')),
                ('status', models.CharField(max_length=100, verbose_name='Статус проверки')),
                ('status_level', models.CharField(default='green', max_length=20, verbose_name='Уровень статуса (green/yellow/red)')),
                ('ci_lower', models.FloatField(default=0.0, verbose_name='Доверительный интервал (нижний, %)')),
                ('ci_upper', models.FloatField(default=0.0, verbose_name='Доверительный интервал (верхний, %)')),
                ('server_seed', models.CharField(blank=True, max_length=64, verbose_name='Server Seed')),
                ('client_seed', models.CharField(blank=True, max_length=64, verbose_name='Client Seed')),
                ('item_stats', models.JSONField(default=list, verbose_name='Статистика по предметам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rng_simulations', to='cases.case', verbose_name='Кейс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
            ],
            options={
                'verbose_name': 'Результат RNG симуляции',
                'verbose_name_plural': 'Результаты RNG симуляций',
                'ordering': ['-created_at'],
            },
        ),
    ]
