# Generated by Django on 2026-09-08
from decimal import Decimal
from django.db import migrations

PARADISE_ITEMS_DATA = [
    {"name": "Gilded Glowing Parachute", "weapon_type": "Parachute", "skin_name": "Gilded Glowing", "rarity": "covert", "value": Decimal("120.00"), "weight": 0.364, "slug": "gilded-glowing-parachute"},
    {"name": "Mega Kitty Parachute", "weapon_type": "Parachute", "skin_name": "Mega Kitty", "rarity": "classified", "value": Decimal("60.00"), "weight": 0.707, "slug": "mega-kitty-parachute"},
    {"name": "Blueyonder Glider", "weapon_type": "Glider", "skin_name": "Blueyonder", "rarity": "covert", "value": Decimal("150.00"), "weight": 0.297, "slug": "blueyonder-glider"},
    {"name": "Boxerbolt Hoverboard", "weapon_type": "Hoverboard", "skin_name": "Boxerbolt", "rarity": "classified", "value": Decimal("75.00"), "weight": 0.568, "slug": "boxerbolt-hoverboard"},
    {"name": "Crimson Fox Set", "weapon_type": "Clothes", "skin_name": "Crimson Fox", "rarity": "classified", "value": Decimal("55.00"), "weight": 0.770, "slug": "crimson-fox-set"},
    {"name": "Space Mascot Headpiece", "weapon_type": "Clothes", "skin_name": "Space Mascot", "rarity": "restricted", "value": Decimal("25.00"), "weight": 1.708, "slug": "space-mascot-headpiece"},
    {"name": "Crimson Fox - Pan", "weapon_type": "Pan", "skin_name": "Crimson Fox", "rarity": "covert", "value": Decimal("180.00"), "weight": 0.253, "slug": "crimson-fox-pan"},
    {"name": "Past Glory Set", "weapon_type": "Clothes", "skin_name": "Past Glory", "rarity": "restricted", "value": Decimal("20.00"), "weight": 2.147, "slug": "past-glory-set"},
    {"name": "Bloody Bite - DP28", "weapon_type": "DP-28", "skin_name": "Bloody Bite", "rarity": "restricted", "value": Decimal("35.00"), "weight": 1.212, "slug": "bloody-bite-dp28"},
    {"name": "The Fangs Set", "weapon_type": "Clothes", "skin_name": "The Fangs", "rarity": "restricted", "value": Decimal("22.00"), "weight": 1.947, "slug": "the-fangs-set"},
    {"name": "Masked Psychic Cover", "weapon_type": "Clothes", "skin_name": "Masked Psychic", "rarity": "restricted", "value": Decimal("12.00"), "weight": 3.640, "slug": "masked-psychic-cover"},
    {"name": "Octosurprise Backpack", "weapon_type": "Backpack", "skin_name": "Octosurprise", "rarity": "restricted", "value": Decimal("30.00"), "weight": 1.418, "slug": "octosurprise-backpack"},
    {"name": "Obsidian Eagle Mask", "weapon_type": "Clothes", "skin_name": "Obsidian Eagle", "rarity": "restricted", "value": Decimal("18.00"), "weight": 2.393, "slug": "obsidian-eagle-mask"},
    {"name": "Blood Raven Parachute", "weapon_type": "Parachute", "skin_name": "Blood Raven", "rarity": "restricted", "value": Decimal("14.00"), "weight": 3.103, "slug": "blood-raven-parachute"},
    {"name": "Neptune's Grasp - Crowbar", "weapon_type": "Crowbar", "skin_name": "Neptune's Grasp", "rarity": "restricted", "value": Decimal("16.00"), "weight": 2.702, "slug": "neptunes-grasp-crowbar"},
    {"name": "Winter Wonderland - Sickle", "weapon_type": "Sickle", "skin_name": "Winter Wonderland", "rarity": "restricted", "value": Decimal("15.00"), "weight": 2.889, "slug": "winter-wonderland-sickle"},
    {"name": "Nightscape Gladiator - PP-19 Bizon", "weapon_type": "PP-19 Bizon", "skin_name": "Nightscape Gladiator", "rarity": "restricted", "value": Decimal("28.00"), "weight": 1.521, "slug": "nightscape-gladiator-pp19"},
    {"name": "Hellfire UAZ", "weapon_type": "Vehicle", "skin_name": "Hellfire", "rarity": "restricted", "value": Decimal("50.00"), "weight": 0.847, "slug": "hellfire-uaz"},
    {"name": "Wonderland Traveler - UMP45", "weapon_type": "UMP45", "skin_name": "Wonderland Traveler", "rarity": "mil_spec", "value": Decimal("5.00"), "weight": 9.059, "slug": "wonderland-traveler-ump45"},
    {"name": "Classic Santa Suit", "weapon_type": "Clothes", "skin_name": "Classic Santa", "rarity": "mil_spec", "value": Decimal("4.00"), "weight": 11.439, "slug": "classic-santa-suit"},
    {"name": "Iron Judge Hat", "weapon_type": "Clothes", "skin_name": "Iron Judge", "rarity": "mil_spec", "value": Decimal("2.00"), "weight": 23.634, "slug": "iron-judge-hat"},
    {"name": "Phantom Fox Mask", "weapon_type": "Clothes", "skin_name": "Phantom Fox", "rarity": "mil_spec", "value": Decimal("3.00"), "weight": 15.457, "slug": "phantom-fox-mask"},
    {"name": "Shadowfire Captain - Kar98K", "weapon_type": "Kar98K", "skin_name": "Shadowfire Captain", "rarity": "mil_spec", "value": Decimal("8.00"), "weight": 5.548, "slug": "shadowfire-captain-kar98k"},
    {"name": "Illusion Judge - Pan", "weapon_type": "Pan", "skin_name": "Illusion Judge", "rarity": "mil_spec", "value": Decimal("7.00"), "weight": 6.377, "slug": "illusion-judge-pan"},
]

def sync_paradise_case(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    Item = apps.get_model('cases', 'Item')
    CaseItem = apps.get_model('cases', 'CaseItem')
    Category = apps.get_model('cases', 'Category')

    category, _ = Category.objects.get_or_create(
        slug='cases-with-skins',
        defaults={'name': 'Кейсы со скинами', 'order': 1}
    )

    case = Case.objects.filter(slug__in=['paradise-eruption', 'paradise_eruption']).first()
    if not case:
        case = Case.objects.filter(name__icontains='извержение').first()

    if not case:
        # In isolated test environments where Paradise Eruption is not seeded,
        # do not inject fixtures into empty test databases.
        return

    case.name = 'Райское извержение'
    case.slug = 'paradise-eruption'
    case.price = Decimal('15.00')
    case.category = category
    case.active = True
    case.save()

    items_map = {}
    for data in PARADISE_ITEMS_DATA:
        item = Item.objects.filter(name=data['name']).first()
        if not item:
            item = Item.objects.create(
                name=data['name'],
                weapon_type=data['weapon_type'],
                skin_name=data['skin_name'],
                rarity=data['rarity'],
                value=data['value'],
                image=f"items/{data['slug']}.png"
            )
        else:
            item.weapon_type = data['weapon_type']
            item.skin_name = data['skin_name']
            item.rarity = data['rarity']
            item.value = data['value']
            if not item.image:
                item.image = f"items/{data['slug']}.png"
            item.save()
        items_map[data['name']] = (item, data['weight'])

    CaseItem.objects.filter(case=case).delete()

    created_case_items = [
        CaseItem(case=case, item=item, weight=weight)
        for item, weight in items_map.values()
    ]
    CaseItem.objects.bulk_create(created_case_items)

def reverse_sync(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_rngsimulationrun'),
    ]

    operations = [
        migrations.RunPython(sync_paradise_case, reverse_sync),
    ]
