# Generated by Django on 2026-09-08
from decimal import Decimal
from django.db import migrations

PARADISE_ITEMS_80_DATA = [
    {"name": "Crimson Fox - Pan", "weight": 0.497},
    {"name": "Blueyonder Glider", "weight": 0.517},
    {"name": "Gilded Glowing Parachute", "weight": 0.562},
    {"name": "Boxerbolt Hoverboard", "weight": 0.733},
    {"name": "Mega Kitty Parachute", "weight": 0.859},
    {"name": "Crimson Fox Set", "weight": 0.917},
    {"name": "Hellfire UAZ", "weight": 0.989},
    {"name": "Bloody Bite - DP28", "weight": 1.333},
    {"name": "Octosurprise Backpack", "weight": 1.528},
    {"name": "Nightscape Gladiator - PP-19 Bizon", "weight": 1.626},
    {"name": "Space Mascot Headpiece", "weight": 1.804},
    {"name": "The Fangs Set", "weight": 2.032},
    {"name": "Past Glory Set", "weight": 2.224},
    {"name": "Obsidian Eagle Mask", "weight": 2.459},
    {"name": "Neptune's Grasp - Crowbar", "weight": 2.755},
    {"name": "Winter Wonderland - Sickle", "weight": 2.933},
    {"name": "Blood Raven Parachute", "weight": 3.137},
    {"name": "Masked Psychic Cover", "weight": 3.652},
    {"name": "Shadowfire Captain - Kar98K", "weight": 5.478},
    {"name": "Illusion Judge - Pan", "weight": 6.270},
    {"name": "Wonderland Traveler - UMP45", "weight": 8.838},
    {"name": "Classic Santa Suit", "weight": 11.115},
    {"name": "Phantom Fox Mask", "weight": 14.959},
    {"name": "Iron Judge Hat", "weight": 22.783},
]

def update_paradise_80_rtp(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    Item = apps.get_model('cases', 'Item')
    CaseItem = apps.get_model('cases', 'CaseItem')

    case = Case.objects.filter(slug__in=['paradise-eruption', 'paradise_eruption']).first()
    if not case:
        case = Case.objects.filter(name__icontains='извержение').first()

    if not case:
        return

    # Update or recreate CaseItem records for Paradise Eruption
    CaseItem.objects.filter(case=case).delete()

    created_case_items = []
    for data in PARADISE_ITEMS_80_DATA:
        item = Item.objects.filter(name=data['name']).first()
        if item:
            created_case_items.append(
                CaseItem(case=case, item=item, weight=data['weight'])
            )

    CaseItem.objects.bulk_create(created_case_items)

def reverse_sync(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_sync_paradise_eruption_24_items_70_rtp'),
    ]

    operations = [
        migrations.RunPython(update_paradise_80_rtp, reverse_sync),
    ]
