# Generated by Django on 2026-09-09
from decimal import Decimal
from django.db import migrations

LAMBORGHINI_ITEMS_DATA = [
    {
        "name": "Lamborghini Invencible Nebula Drift",
        "weapon_type": "Vehicle",
        "skin_name": "Invencible Nebula Drift",
        "rarity": "knife",
        "value": Decimal("45000.00"),
        "weight": 0.566,
        "slug": "lamborghini-invencible-nebula-drift"
    },
    {
        "name": "Bugatti La Voiture Noire (Warrior)",
        "weapon_type": "Vehicle",
        "skin_name": "La Voiture Noire (Warrior)",
        "rarity": "covert",
        "value": Decimal("30000.00"),
        "weight": 0.775,
        "slug": "bugatti-la-voiture-noire-warrior"
    },
    {
        "name": "Koenigsegg Jesko (Dawn)",
        "weapon_type": "Vehicle",
        "skin_name": "Jesko (Dawn)",
        "rarity": "covert",
        "value": Decimal("25000.00"),
        "weight": 0.893,
        "slug": "koenigsegg-jesko-dawn"
    },
    {
        "name": "Koenigsegg One:1 Phoenix",
        "weapon_type": "Vehicle",
        "skin_name": "One:1 Phoenix",
        "rarity": "covert",
        "value": Decimal("22000.00"),
        "weight": 0.986,
        "slug": "koenigsegg-one-1-phoenix"
    },
    {
        "name": "Lamborghini Aventador SVJ Blue",
        "weapon_type": "Vehicle",
        "skin_name": "Aventador SVJ Blue",
        "rarity": "covert",
        "value": Decimal("20000.00"),
        "weight": 1.061,
        "slug": "lamborghini-aventador-svj-blue"
    },
    {
        "name": "Koenigsegg Gemera (Rainbow)",
        "weapon_type": "Vehicle",
        "skin_name": "Gemera (Rainbow)",
        "rarity": "covert",
        "value": Decimal("18000.00"),
        "weight": 1.152,
        "slug": "koenigsegg-gemera-rainbow"
    },
    {
        "name": "Lamborghini Estoque Oro",
        "weapon_type": "Vehicle",
        "skin_name": "Estoque Oro",
        "rarity": "covert",
        "value": Decimal("15000.00"),
        "weight": 1.326,
        "slug": "lamborghini-estoque-oro"
    },
    {
        "name": "Lamborghini Urus Pink",
        "weapon_type": "Vehicle",
        "skin_name": "Urus Pink",
        "rarity": "covert",
        "value": Decimal("12000.00"),
        "weight": 1.577,
        "slug": "lamborghini-urus-pink"
    },
    {
        "name": "Maserati MC20 Bianco Audace",
        "weapon_type": "Vehicle",
        "skin_name": "MC20 Bianco Audace",
        "rarity": "covert",
        "value": Decimal("10000.00"),
        "weight": 1.816,
        "slug": "maserati-mc20-bianco-audace"
    },
    {
        "name": "Koenigsegg Gemera (Silver Gray)",
        "weapon_type": "Vehicle",
        "skin_name": "Gemera (Silver Gray)",
        "rarity": "covert",
        "value": Decimal("9000.00"),
        "weight": 1.971,
        "slug": "koenigsegg-gemera-silver-gray"
    },
    {
        "name": "Bramble Overlord Set",
        "weapon_type": "Clothes",
        "skin_name": "Bramble Overlord",
        "rarity": "knife",
        "value": Decimal("7500.00"),
        "weight": 2.270,
        "slug": "bramble-overlord-set"
    },
    {
        "name": "Solar Knight Set",
        "weapon_type": "Clothes",
        "skin_name": "Solar Knight",
        "rarity": "knife",
        "value": Decimal("6500.00"),
        "weight": 2.537,
        "slug": "solar-knight-set"
    },
    {
        "name": "Serpengleam Set",
        "weapon_type": "Clothes",
        "skin_name": "Serpengleam",
        "rarity": "knife",
        "value": Decimal("5500.00"),
        "weight": 2.887,
        "slug": "serpengleam-set"
    },
    {
        "name": "Dandy Groovster Set",
        "weapon_type": "Clothes",
        "skin_name": "Dandy Groovster",
        "rarity": "knife",
        "value": Decimal("4800.00"),
        "weight": 3.209,
        "slug": "dandy-groovster-set"
    },
    {
        "name": "AKM (Cobra)",
        "weapon_type": "AKM",
        "skin_name": "Cobra",
        "rarity": "knife",
        "value": Decimal("4200.00"),
        "weight": 3.559,
        "slug": "akm-cobra"
    },
    {
        "name": "AKM (Refined)",
        "weapon_type": "AKM",
        "skin_name": "Refined",
        "rarity": "knife",
        "value": Decimal("3600.00"),
        "weight": 4.011,
        "slug": "akm-refined"
    },
    {
        "name": "MG3 (Refined)",
        "weapon_type": "MG3",
        "skin_name": "Refined",
        "rarity": "knife",
        "value": Decimal("3200.00"),
        "weight": 4.394,
        "slug": "mg3-refined"
    },
    {
        "name": "Sting Queen Set",
        "weapon_type": "Clothes",
        "skin_name": "Sting Queen",
        "rarity": "covert",
        "value": Decimal("2800.00"),
        "weight": 4.873,
        "slug": "sting-queen-set"
    },
    {
        "name": "Bloodmoon Assassin Set",
        "weapon_type": "Clothes",
        "skin_name": "Bloodmoon Assassin",
        "rarity": "covert",
        "value": Decimal("2400.00"),
        "weight": 5.492,
        "slug": "bloodmoon-assassin-set"
    },
    {
        "name": "Space Mascot Set",
        "weapon_type": "Clothes",
        "skin_name": "Space Mascot",
        "rarity": "covert",
        "value": Decimal("2000.00"),
        "weight": 6.326,
        "slug": "space-mascot-set"
    },
    {
        "name": "Tesla Roadster (Amethyst)",
        "weapon_type": "Vehicle",
        "skin_name": "Roadster (Amethyst)",
        "rarity": "classified",
        "value": Decimal("1600.00"),
        "weight": 7.520,
        "slug": "tesla-roadster-amethyst"
    },
    {
        "name": "Exotic Coin",
        "weapon_type": "Currency",
        "skin_name": "Exotic Coin",
        "rarity": "covert",
        "value": Decimal("1200.00"),
        "weight": 9.399,
        "slug": "exotic-coin"
    },
    {
        "name": "Password Letter (White)",
        "weapon_type": "Document",
        "skin_name": "Password Letter (White)",
        "rarity": "classified",
        "value": Decimal("800.00"),
        "weight": 12.871,
        "slug": "password-letter-white"
    },
    {
        "name": "Dog Tag",
        "weapon_type": "Accessory",
        "skin_name": "Dog Tag",
        "rarity": "restricted",
        "value": Decimal("500.00"),
        "weight": 18.529,
        "slug": "dog-tag"
    },
]


def setup_lamborghini_case(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    Item = apps.get_model('cases', 'Item')
    CaseItem = apps.get_model('cases', 'CaseItem')
    Category = apps.get_model('cases', 'Category')

    category, _ = Category.objects.get_or_create(
        slug='cases-with-skins',
        defaults={'name': 'Кейсы со скинами', 'order': 1}
    )

    case, created = Case.objects.get_or_create(
        slug='lamborghini',
        defaults={
            'name': 'Lamborghini',
            'category': category,
            'price': Decimal('5000.00'),
            'active': True,
            'is_popular': True,
            'is_new': True,
            'color_theme': 'godlike-gold',
            'image': 'cases/lamborghini.jpg'
        }
    )

    if not created:
        case.name = 'Lamborghini'
        case.price = Decimal('5000.00')
        case.category = category
        case.active = True
        case.is_popular = True
        case.is_new = True
        case.color_theme = 'godlike-gold'
        if not case.image:
            case.image = 'cases/lamborghini.jpg'
        case.save()

    items_map = {}
    for data in LAMBORGHINI_ITEMS_DATA:
        item, _ = Item.objects.get_or_create(
            name=data['name'],
            defaults={
                'weapon_type': data['weapon_type'],
                'skin_name': data['skin_name'],
                'rarity': data['rarity'],
                'value': data['value'],
                'image': f"items/{data['slug']}.png"
            }
        )
        if not item.image:
            item.image = f"items/{data['slug']}.png"
            item.save(update_fields=['image'])
        items_map[data['name']] = item

    CaseItem.objects.filter(case=case).delete()

    created_case_items = []
    for data in LAMBORGHINI_ITEMS_DATA:
        item = items_map[data['name']]
        created_case_items.append(
            CaseItem(
                case=case,
                item=item,
                weight=data['weight']
            )
        )

    CaseItem.objects.bulk_create(created_case_items)


def reverse_setup(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_update_paradise_eruption_80_rtp'),
    ]

    operations = [
        migrations.RunPython(setup_lamborghini_case, reverse_setup),
    ]
