# Generated by Django 5.2.17 on 2026-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_import_standalone_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='game',
            field=models.CharField(db_index=True, default='PUBG', max_length=50, verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, default='skin', max_length=100, verbose_name='Тип предмета'),
        ),
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='item',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='source_image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Source Image URL'),
        ),
        migrations.AddField(
            model_name='item',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('knife', '★ Нож / Особое (Золотое)'), ('covert', 'Тайное (Красное)'), ('classified', 'Засекреченное (Розовое)'), ('restricted', 'Запрещенное (Фиолетовое)'), ('mil_spec', 'Армейское качество (Синее)'), ('industrial', 'Промышленное качество (Голубое)'), ('consumer', 'Ширпотреб (Серое)'), ('mythic', 'Мифический (Золотой)'), ('legendary', 'Легендарный (Красный)'), ('epic', 'Эпический (Розовый)'), ('rare', 'Редкий (Синий)'), ('uncommon', 'Необычный (Зеленый)'), ('common', 'Обычный (Серый)')], default='mil_spec', max_length=30, verbose_name='Редкость'),
        ),
    ]
