# Generated by Django 5.2.17 on 2026-09-10 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_item_game_item_item_type_item_quality_item_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubgImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID сессии импорта')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла архива')),
                ('zip_path', models.CharField(max_length=500, verbose_name='Путь к сохранённому архиву')),
                ('filesize_bytes', models.BigIntegerField(default=0, verbose_name='Размер архива (байт)')),
                ('total_items', models.IntegerField(default=0, verbose_name='Всего предметов в архиве')),
                ('new_items_count', models.IntegerField(default=0, verbose_name='Количество новых (NEW)')),
                ('existing_items_count', models.IntegerField(default=0, verbose_name='Количество существующих (EXISTING)')),
                ('error_items_count', models.IntegerField(default=0, verbose_name='Количество ошибок валидации')),
                ('total_images', models.IntegerField(default=0, verbose_name='Количество изображений')),
                ('status', models.CharField(choices=[('preview', 'Ожидает подтверждения (Preview)'), ('importing', 'Выполняется импорт'), ('completed', 'Импорт успешно завершён'), ('failed', 'Ошибка при импорте'), ('cancelled', 'Отменён пользователем')], db_index=True, default='preview', max_length=20, verbose_name='Статус')),
                ('mode', models.CharField(default='add_only', max_length=30, verbose_name='Режим импорта')),
                ('summary_data', models.JSONField(blank=True, default=dict, verbose_name='Итоговая статистика')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Сессия импорта PUBG',
                'verbose_name_plural': 'Сессии импорта PUBG',
                'ordering': ['-created_at'],
            },
        ),
    ]
