# Generated by Django 5.2.17 on 2026-09-11 19:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_update_all_supercar_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRtpBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_rtp', models.DecimalField(decimal_places=2, default=Decimal('95.00'), help_text='Целевой процент возврата игроку (например 95.00 = 95%)', max_digits=5, verbose_name='RTP (%)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.CharField(blank=True, help_text='Внутренний комментарий администратора', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtp_bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персональный бонус RTP',
                'verbose_name_plural': 'Персональные бонусы RTP',
                'ordering': ['-created_at'],
            },
        ),
    ]
