# Generated by Django 5.2.17 on 2026-09-16 01:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_personalrtpbonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggerPromoCode',
            fields=[
            ],
            options={
                'verbose_name': 'Промокод блогера',
                'verbose_name_plural': 'Промокоды блогеров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.promocode',),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='bonus_type',
            field=models.CharField(choices=[('coins', 'UC / Баланс (UC)'), ('percentage', 'Процент к депозиту (%)'), ('free_case_opens', 'Бесплатные открытия кейса'), ('blogger', 'Промокод блогера (60 UC = 13 000 UZS)')], default='coins', max_length=30, verbose_name='Тип бонуса'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='bonus_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Значение бонуса (UC / % / Кол-во)'),
        ),
    ]
