# Generated by Django 5.2.17 on 2026-08-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_input_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма вложенных предметов ($)')),
                ('items_count', models.PositiveIntegerField(default=3, verbose_name='Количество вложенных предметов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата контракта')),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_rewards', to='cases.item', verbose_name='Полученный скин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контракт обмена',
                'verbose_name_plural': 'Контракты обмена',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_items', to='contracts.contract', verbose_name='Контракт')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.item', verbose_name='Предмет')),
            ],
        ),
    ]
