# Generated by Django 5.2.17 on 2026-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_input_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма вложенных предметов (UC)'),
        ),
    ]
