# Generated by Django 5.2.17 on 2026-08-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(verbose_name='Шанс успеха (%)')),
                ('roll', models.FloatField(verbose_name='Выпавшее число (%)')),
                ('is_success', models.BooleanField(verbose_name='Успешен')),
                ('server_seed', models.CharField(blank=True, max_length=64, verbose_name='Server Seed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_from', to='cases.item', verbose_name='Исходный скин')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_to', to='cases.item', verbose_name='Целевой скин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка апгрейда',
                'verbose_name_plural': 'Попытки апгрейда',
                'ordering': ['-created_at'],
            },
        ),
    ]
