# Generated by Django 5.2.17 on 2026-08-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продан')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи ($)')),
                ('source', models.CharField(choices=[('case', 'Открытие кейса'), ('upgrade', 'Апгрейд'), ('contract', 'Контракт'), ('battle', 'Битва кейсов'), ('admin', 'Начислено администратором')], default='case', max_length=20, verbose_name='Источник получения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='cases.item', verbose_name='Предмет')),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_drops', to='cases.opening', verbose_name='Связанное открытие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предмет в инвентаре',
                'verbose_name_plural': 'Инвентарь пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
