# Generated by Django 5.2.17 on 2026-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_sold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи (UC)'),
        ),
    ]
